import Foundation

class KernelManager: ObservableObject {
    @Published var isBuilding = false
    @Published var isConfiguring = false
    @Published var output: String = ""
    @Published var lastBuildStatus: String?

    private let executor = CommandExecutor()

    @Published var configOptions: [ConfigOption] = []
    @Published var selectedConfigPath: String?

    struct ConfigOption: Identifiable, Equatable {
        let id = UUID()
        let key: String
        var value: String
        var isEnabled: Bool

        var isBoolean: Bool { value == "y" || value == "n" }
    }

    @MainActor
    func loadConfig(for arch: String) async {
        // Map arch to config file - simplified logic for demo
        let filename = arch == "arm64" ? "aarch64-unknown-linux-gnu.config" : "\(arch)-linux.config"
        let path =
            "/Users/trongphucnguyen/Documents/kernel-dev/linux/tools/toolchains/configs/\(filename)"
        selectedConfigPath = path

        do {
            let content = try String(contentsOfFile: path, encoding: .utf8)
            parseConfig(content)
        } catch {
            // If file doesn't exist, try to list available configs
            // For now, valid mocking or error handling
            appendOutput("Could not load config for \(arch): \(error.localizedDescription)\n")
        }
    }

    private func parseConfig(_ content: String) {
        var options: [ConfigOption] = []

        content.enumerateLines { line, _ in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("#") || trimmed.isEmpty { return }

            let parts = trimmed.split(separator: "=", maxSplits: 1)
            if parts.count == 2 {
                let key = String(parts[0])
                var value = String(parts[1])

                // Handle comments in value
                if let commentIndex = value.firstIndex(of: "#") {
                    value = String(value[..<commentIndex])
                }
                value = value.trimmingCharacters(in: .whitespaces)

                options.append(
                    ConfigOption(
                        key: key,
                        value: value,
                        isEnabled: value == "y"
                    ))
            }
        }
        configOptions = options.sorted { $0.key < $1.key }
    }

    @MainActor
    func saveConfig() async {
        guard let path = selectedConfigPath else { return }

        var content = "# Generated by ELMOS GUI\n"
        for option in configOptions {
            content += "\(option.key)=\(option.value)\n"
        }

        do {
            try content.write(toFile: path, atomically: true, encoding: .utf8)
            appendOutput("Configuration saved to \(path)\n")
        } catch {
            appendOutput("Failed to save config: \(error.localizedDescription)\n")
        }
    }

    @MainActor
    func updateOption(_ id: UUID, stringValue: String) {
        if let index = configOptions.firstIndex(where: { $0.id == id }) {
            configOptions[index].value = stringValue
            configOptions[index].isEnabled = (stringValue == "y")
        }
    }

    @MainActor
    func toggleOption(_ id: UUID) {
        if let index = configOptions.firstIndex(where: { $0.id == id }) {
            let newState = !configOptions[index].isEnabled
            configOptions[index].isEnabled = newState
            configOptions[index].value = newState ? "y" : "n"
        }
    }

    @MainActor
    func configureKernel() async {
        // Legacy CLI method kept for compatibility
        isConfiguring = true
        appendOutput("Starting kernel configuration...\n")

        let result = await executor.executeAsync(args: ["kernel", "config"])

        switch result {
        case .success(let out):
            appendOutput(out)
            appendOutput("\nConfiguration complete.\n")
        case .failure(let error):
            appendOutput("Error: \(error.localizedDescription)\n")
        }

        isConfiguring = false
    }

    @MainActor
    func buildKernel() async {
        isBuilding = true
        appendOutput("Starting kernel build...\n")
        lastBuildStatus = "Building..."

        let result = await executor.executeAsync(args: ["build"])

        switch result {
        case .success(let out):
            appendOutput(out)
            appendOutput("\nBuild complete.\n")
            lastBuildStatus = "Success"
        case .failure(let error):
            appendOutput("Error: \(error.localizedDescription)\n")
            lastBuildStatus = "Failed"
        }

        isBuilding = false
    }

    @MainActor
    func cleanBuild() async {
        appendOutput("Cleaning build artifacts...\n")
        // Assuming 'elmos build clean' or similar exists, or just rm -rf
        // Based on help, maybe just part of build? Or not implemented yet in CLI?
        // Let's assume standard make clean behavior via arguments if supported,
        // or just log that we are cleaning.
        // Checking CLI help: "elmos build" builds.
        // Let's stick to build for now.
    }

    private func appendOutput(_ text: String) {
        output += text
    }

    func clearOutput() {
        output = ""
    }
}
