# ELMOS - Embedded Linux on MacOS
# Taskfile for building and installing the elmos CLI
# https://taskfile.dev

version: '3'

vars:
  BUILD_DIR: build
  BINARY: "{{.BUILD_DIR}}/elmos"
  PREFIX: /usr/local
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: >-
    -X github.com/NguyenTrongPhuc552003/elmos/pkg/version.Version={{.VERSION}}
    -X github.com/NguyenTrongPhuc552003/elmos/pkg/version.Commit={{.COMMIT}}
    -X github.com/NguyenTrongPhuc552003/elmos/pkg/version.BuildDate={{.DATE}}
  GOBIN:
    sh: go env GOPATH

tasks:
  # ============================================================================
  # Default & Core Build
  # ============================================================================

  default:
    desc: Build the elmos binary
    cmds:
      - task: build

  build:
    desc: Build the elmos binary
    cmds:
      - echo "Building {{.BINARY}}..."
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags "{{.LDFLAGS}}" -o {{.BINARY}} .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY}}"

  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf completions
      - rm -f coverage.out coverage.html
      - go clean

  # ============================================================================
  # Development Workflow (dev:*)
  # ============================================================================

  dev:deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  dev:fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  dev:lint:
    desc: Run linter (golangci-lint or go vet)
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run
        else
          echo "golangci-lint not installed, running go vet..."
          go vet ./...
        fi

  dev:check:
    desc: Run fmt, lint, and test (pre-commit style)
    cmds:
      - task: dev:fmt
      - task: dev:lint


  dev:setup:
    desc: Full dev setup (deps + build + init workspace)
    cmds:
      - task: dev:deps
      - task: build
      - task: elmos:init



  # ============================================================================
  # elmos CLI Wrappers (elmos:*)
  # ============================================================================

  elmos:init:
    desc: Initialize elmos workspace (mount volume)
    deps: [build]
    cmds:
      - ./{{.BINARY}} init

  elmos:exit:
    desc: Exit elmos workspace (unmount volume)
    deps: [build]
    cmds:
      - ./{{.BINARY}} exit

  elmos:status:
    desc: Show workspace status
    deps: [build]
    cmds:
      - ./{{.BINARY}} status

  elmos:doctor:
    desc: Run elmos doctor (environment check)
    deps: [build]
    cmds:
      - ./{{.BINARY}} doctor

  elmos:tui:
    desc: Launch elmos TUI
    deps: [build]
    cmds:
      - ./{{.BINARY}} tui

  # ============================================================================
  # Installation (install:*)
  # ============================================================================

  install:
    desc: Install to GOPATH/bin
    deps: [build]
    cmds:
      - echo "Installing to {{.GOBIN}}/bin..."
      - mkdir -p {{.GOBIN}}/bin
      - cp {{.BINARY}} {{.GOBIN}}/bin/

  install:global:
    desc: Install to /usr/local/bin (requires sudo)
    deps: [build]
    cmds:
      - echo "Installing to {{.PREFIX}}/bin..."
      - sudo cp {{.BINARY}} {{.PREFIX}}/bin/

  uninstall:
    desc: Remove from GOPATH/bin
    cmds:
      - rm -f {{.GOBIN}}/bin/elmos

  # ============================================================================
  # Release (release:*)
  # ============================================================================

  release:darwin:
    desc: Build for macOS platforms (arm64 + amd64)
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - echo "Building for darwin/arm64..."
      - GOOS=darwin GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o {{.BINARY}}-darwin-arm64 .
      - echo "Building for darwin/amd64..."
      - GOOS=darwin GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o {{.BINARY}}-darwin-amd64 .

  release:completions:
    desc: Generate shell completions
    deps: [build]
    cmds:
      - mkdir -p completions
      - ./{{.BINARY}} completion bash > completions/elmos.bash
      - ./{{.BINARY}} completion zsh > completions/_elmos
      - ./{{.BINARY}} completion fish > completions/elmos.fish
      - 'echo "Completions generated in completions/"'

  release:all:
    desc: Full release (all platforms + completions)
    cmds:
      - task: release:darwin
      - task: release:completions

  release:homebrew:
    desc: Generate Homebrew formula
    cmds:
      - |
        cat <<EOF
        class Elmos < Formula
          desc "Embedded Linux development on macOS - native kernel builds"
          homepage "https://github.com/NguyenTrongPhuc552003/elmos"
          version "{{.VERSION}}"
          license "MIT"

          depends_on "llvm"
          depends_on "lld"
          depends_on "gnu-sed"
          depends_on "make"
          depends_on "libelf"
          depends_on "qemu"
          depends_on "e2fsprogs"
          depends_on "coreutils"

          def install
            bin.install "elmos"
          end

          test do
            system "\#{bin}/elmos", "version"
          end
        end
        EOF
