// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLine_Level int32

const (
	LogLine_DEBUG LogLine_Level = 0
	LogLine_INFO  LogLine_Level = 1
	LogLine_WARN  LogLine_Level = 2
	LogLine_ERROR LogLine_Level = 3
)

// Enum value maps for LogLine_Level.
var (
	LogLine_Level_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
	}
	LogLine_Level_value = map[string]int32{
		"DEBUG": 0,
		"INFO":  1,
		"WARN":  2,
		"ERROR": 3,
	}
)

func (x LogLine_Level) Enum() *LogLine_Level {
	p := new(LogLine_Level)
	*p = x
	return p
}

func (x LogLine_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLine_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_proto_enumTypes[0].Descriptor()
}

func (LogLine_Level) Type() protoreflect.EnumType {
	return &file_api_proto_common_proto_enumTypes[0]
}

func (x LogLine_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLine_Level.Descriptor instead.
func (LogLine_Level) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{2, 0}
}

// BuildProgress represents progress updates during build operations.
type BuildProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*BuildProgress_Stage
	//	*BuildProgress_Log
	//	*BuildProgress_Error
	//	*BuildProgress_Complete
	Event         isBuildProgress_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildProgress) Reset() {
	*x = BuildProgress{}
	mi := &file_api_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildProgress) ProtoMessage() {}

func (x *BuildProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildProgress.ProtoReflect.Descriptor instead.
func (*BuildProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *BuildProgress) GetEvent() isBuildProgress_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BuildProgress) GetStage() *BuildStage {
	if x != nil {
		if x, ok := x.Event.(*BuildProgress_Stage); ok {
			return x.Stage
		}
	}
	return nil
}

func (x *BuildProgress) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Event.(*BuildProgress_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *BuildProgress) GetError() *BuildError {
	if x != nil {
		if x, ok := x.Event.(*BuildProgress_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *BuildProgress) GetComplete() *BuildComplete {
	if x != nil {
		if x, ok := x.Event.(*BuildProgress_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isBuildProgress_Event interface {
	isBuildProgress_Event()
}

type BuildProgress_Stage struct {
	Stage *BuildStage `protobuf:"bytes,1,opt,name=stage,proto3,oneof"`
}

type BuildProgress_Log struct {
	Log *LogLine `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type BuildProgress_Error struct {
	Error *BuildError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type BuildProgress_Complete struct {
	Complete *BuildComplete `protobuf:"bytes,4,opt,name=complete,proto3,oneof"`
}

func (*BuildProgress_Stage) isBuildProgress_Event() {}

func (*BuildProgress_Log) isBuildProgress_Event() {}

func (*BuildProgress_Error) isBuildProgress_Event() {}

func (*BuildProgress_Complete) isBuildProgress_Event() {}

// BuildStage represents a build stage with progress information.
type BuildStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                   // Stage name
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`                          // 0-100
	CurrentFile   int32                  `protobuf:"varint,3,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"` // Current file number (optional)
	TotalFiles    int32                  `protobuf:"varint,4,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`    // Total files to process (optional)
	Component     string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`                         // Component being built (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStage) Reset() {
	*x = BuildStage{}
	mi := &file_api_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStage) ProtoMessage() {}

func (x *BuildStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStage.ProtoReflect.Descriptor instead.
func (*BuildStage) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *BuildStage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildStage) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *BuildStage) GetCurrentFile() int32 {
	if x != nil {
		return x.CurrentFile
	}
	return 0
}

func (x *BuildStage) GetTotalFiles() int32 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *BuildStage) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

// LogLine represents a log message.
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLine_Level          `protobuf:"varint,1,opt,name=level,proto3,enum=elmos.v1.LogLine_Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_api_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *LogLine) GetLevel() LogLine_Level {
	if x != nil {
		return x.Level
	}
	return LogLine_DEBUG
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// BuildError represents a build error.
type BuildError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`           // Source file (optional)
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`          // Line number (optional)
	Column        string                 `protobuf:"bytes,4,opt,name=column,proto3" json:"column,omitempty"`       // Column (optional)
	Component     string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"` // Component name (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildError) Reset() {
	*x = BuildError{}
	mi := &file_api_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildError) ProtoMessage() {}

func (x *BuildError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildError.ProtoReflect.Descriptor instead.
func (*BuildError) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *BuildError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildError) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *BuildError) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *BuildError) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *BuildError) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

// BuildComplete indicates build completion.
type BuildComplete struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DurationMs     int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	InstallPath    string                 `protobuf:"bytes,3,opt,name=install_path,json=installPath,proto3" json:"install_path,omitempty"`             // Installation path (optional)
	ImagePath      string                 `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`                   // Image path for kernel builds (optional)
	ImageSizeBytes int64                  `protobuf:"varint,5,opt,name=image_size_bytes,json=imageSizeBytes,proto3" json:"image_size_bytes,omitempty"` // Image size (optional)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildComplete) Reset() {
	*x = BuildComplete{}
	mi := &file_api_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildComplete) ProtoMessage() {}

func (x *BuildComplete) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildComplete.ProtoReflect.Descriptor instead.
func (*BuildComplete) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *BuildComplete) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildComplete) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BuildComplete) GetInstallPath() string {
	if x != nil {
		return x.InstallPath
	}
	return ""
}

func (x *BuildComplete) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *BuildComplete) GetImageSizeBytes() int64 {
	if x != nil {
		return x.ImageSizeBytes
	}
	return 0
}

// CleanRequest represents a clean operation request.
type CleanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeepClean     bool                   `protobuf:"varint,1,opt,name=deep_clean,json=deepClean,proto3" json:"deep_clean,omitempty"` // Deep clean vs normal clean
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanRequest) Reset() {
	*x = CleanRequest{}
	mi := &file_api_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanRequest) ProtoMessage() {}

func (x *CleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanRequest.ProtoReflect.Descriptor instead.
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *CleanRequest) GetDeepClean() bool {
	if x != nil {
		return x.DeepClean
	}
	return false
}

// CleanResponse represents a clean operation response.
type CleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanResponse) Reset() {
	*x = CleanResponse{}
	mi := &file_api_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanResponse) ProtoMessage() {}

func (x *CleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanResponse.ProtoReflect.Descriptor instead.
func (*CleanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *CleanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CleanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_common_proto protoreflect.FileDescriptor

const file_api_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/common.proto\x12\belmos.v1\"\xd2\x01\n" +
	"\rBuildProgress\x12,\n" +
	"\x05stage\x18\x01 \x01(\v2\x14.elmos.v1.BuildStageH\x00R\x05stage\x12%\n" +
	"\x03log\x18\x02 \x01(\v2\x11.elmos.v1.LogLineH\x00R\x03log\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x14.elmos.v1.BuildErrorH\x00R\x05error\x125\n" +
	"\bcomplete\x18\x04 \x01(\v2\x17.elmos.v1.BuildCompleteH\x00R\bcompleteB\a\n" +
	"\x05event\"\x9e\x01\n" +
	"\n" +
	"BuildStage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12!\n" +
	"\fcurrent_file\x18\x03 \x01(\x05R\vcurrentFile\x12\x1f\n" +
	"\vtotal_files\x18\x04 \x01(\x05R\n" +
	"totalFiles\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\"\xa8\x01\n" +
	"\aLogLine\x12-\n" +
	"\x05level\x18\x01 \x01(\x0e2\x17.elmos.v1.LogLine.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"1\n" +
	"\x05Level\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"\x84\x01\n" +
	"\n" +
	"BuildError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\tR\x06column\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\"\xb6\x01\n" +
	"\rBuildComplete\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12!\n" +
	"\finstall_path\x18\x03 \x01(\tR\vinstallPath\x12\x1d\n" +
	"\n" +
	"image_path\x18\x04 \x01(\tR\timagePath\x12(\n" +
	"\x10image_size_bytes\x18\x05 \x01(\x03R\x0eimageSizeBytes\"-\n" +
	"\fCleanRequest\x12\x1d\n" +
	"\n" +
	"deep_clean\x18\x01 \x01(\bR\tdeepClean\"C\n" +
	"\rCleanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB8Z6github.com/NguyenTrongPhuc552003/elmos/api/proto;protob\x06proto3"

var (
	file_api_proto_common_proto_rawDescOnce sync.Once
	file_api_proto_common_proto_rawDescData []byte
)

func file_api_proto_common_proto_rawDescGZIP() []byte {
	file_api_proto_common_proto_rawDescOnce.Do(func() {
		file_api_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_proto_rawDesc), len(file_api_proto_common_proto_rawDesc)))
	})
	return file_api_proto_common_proto_rawDescData
}

var file_api_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_common_proto_goTypes = []any{
	(LogLine_Level)(0),    // 0: elmos.v1.LogLine.Level
	(*BuildProgress)(nil), // 1: elmos.v1.BuildProgress
	(*BuildStage)(nil),    // 2: elmos.v1.BuildStage
	(*LogLine)(nil),       // 3: elmos.v1.LogLine
	(*BuildError)(nil),    // 4: elmos.v1.BuildError
	(*BuildComplete)(nil), // 5: elmos.v1.BuildComplete
	(*CleanRequest)(nil),  // 6: elmos.v1.CleanRequest
	(*CleanResponse)(nil), // 7: elmos.v1.CleanResponse
}
var file_api_proto_common_proto_depIdxs = []int32{
	2, // 0: elmos.v1.BuildProgress.stage:type_name -> elmos.v1.BuildStage
	3, // 1: elmos.v1.BuildProgress.log:type_name -> elmos.v1.LogLine
	4, // 2: elmos.v1.BuildProgress.error:type_name -> elmos.v1.BuildError
	5, // 3: elmos.v1.BuildProgress.complete:type_name -> elmos.v1.BuildComplete
	0, // 4: elmos.v1.LogLine.level:type_name -> elmos.v1.LogLine.Level
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_common_proto_init() }
func file_api_proto_common_proto_init() {
	if File_api_proto_common_proto != nil {
		return
	}
	file_api_proto_common_proto_msgTypes[0].OneofWrappers = []any{
		(*BuildProgress_Stage)(nil),
		(*BuildProgress_Log)(nil),
		(*BuildProgress_Error)(nil),
		(*BuildProgress_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_proto_rawDesc), len(file_api_proto_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_proto_goTypes,
		DependencyIndexes: file_api_proto_common_proto_depIdxs,
		EnumInfos:         file_api_proto_common_proto_enumTypes,
		MessageInfos:      file_api_proto_common_proto_msgTypes,
	}.Build()
	File_api_proto_common_proto = out.File
	file_api_proto_common_proto_goTypes = nil
	file_api_proto_common_proto_depIdxs = nil
}
