// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/kernel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                // Kernel version (e.g., "v6.18")
	RepoUrl       string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"` // Custom repo URL (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_api_proto_kernel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{0}
}

func (x *CloneRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CloneRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

type CloneProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      int32                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`    // Status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneProgress) Reset() {
	*x = CloneProgress{}
	mi := &file_api_proto_kernel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneProgress) ProtoMessage() {}

func (x *CloneProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneProgress.ProtoReflect.Descriptor instead.
func (*CloneProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{1}
}

func (x *CloneProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *CloneProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    string                 `protobuf:"bytes,1,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`                                                   // "defconfig", "menuconfig", "oldconfig"
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional config options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_api_proto_kernel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *ConfigureRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_api_proto_kernel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []string               `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`  // Build targets: ["Image", "dtbs", "modules"]
	Jobs          int32                  `protobuf:"varint,2,opt,name=jobs,proto3" json:"jobs,omitempty"`       // Number of parallel jobs (0 = auto)
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`        // Target architecture
	Verbose       bool                   `protobuf:"varint,4,opt,name=verbose,proto3" json:"verbose,omitempty"` // Verbose build output
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_api_proto_kernel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{4}
}

func (x *BuildRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *BuildRequest) GetJobs() int32 {
	if x != nil {
		return x.Jobs
	}
	return 0
}

func (x *BuildRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *BuildRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

type KernelStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelStatusRequest) Reset() {
	*x = KernelStatusRequest{}
	mi := &file_api_proto_kernel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelStatusRequest) ProtoMessage() {}

func (x *KernelStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelStatusRequest.ProtoReflect.Descriptor instead.
func (*KernelStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{5}
}

type KernelStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cloned         bool                   `protobuf:"varint,1,opt,name=cloned,proto3" json:"cloned,omitempty"`
	Configured     bool                   `protobuf:"varint,2,opt,name=configured,proto3" json:"configured,omitempty"`
	Built          bool                   `protobuf:"varint,3,opt,name=built,proto3" json:"built,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Arch           string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	ImagePath      string                 `protobuf:"bytes,6,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ImageSizeBytes int64                  `protobuf:"varint,7,opt,name=image_size_bytes,json=imageSizeBytes,proto3" json:"image_size_bytes,omitempty"`
	LastBuildTime  string                 `protobuf:"bytes,8,opt,name=last_build_time,json=lastBuildTime,proto3" json:"last_build_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KernelStatus) Reset() {
	*x = KernelStatus{}
	mi := &file_api_proto_kernel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelStatus) ProtoMessage() {}

func (x *KernelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelStatus.ProtoReflect.Descriptor instead.
func (*KernelStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{6}
}

func (x *KernelStatus) GetCloned() bool {
	if x != nil {
		return x.Cloned
	}
	return false
}

func (x *KernelStatus) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *KernelStatus) GetBuilt() bool {
	if x != nil {
		return x.Built
	}
	return false
}

func (x *KernelStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KernelStatus) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *KernelStatus) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *KernelStatus) GetImageSizeBytes() int64 {
	if x != nil {
		return x.ImageSizeBytes
	}
	return 0
}

func (x *KernelStatus) GetLastBuildTime() string {
	if x != nil {
		return x.LastBuildTime
	}
	return ""
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Max versions to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_api_proto_kernel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{7}
}

func (x *ListVersionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []string               `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_api_proto_kernel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kernel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kernel_proto_rawDescGZIP(), []int{8}
}

func (x *ListVersionsResponse) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_api_proto_kernel_proto protoreflect.FileDescriptor

const file_api_proto_kernel_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/kernel.proto\x12\belmos.v1\x1a\x16api/proto/common.proto\"C\n" +
	"\fCloneRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\"E\n" +
	"\rCloneProgress\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb2\x01\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\vconfig_type\x18\x01 \x01(\tR\n" +
	"configType\x12A\n" +
	"\aoptions\x18\x02 \x03(\v2'.elmos.v1.ConfigureRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"j\n" +
	"\fBuildRequest\x12\x18\n" +
	"\atargets\x18\x01 \x03(\tR\atargets\x12\x12\n" +
	"\x04jobs\x18\x02 \x01(\x05R\x04jobs\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x18\n" +
	"\averbose\x18\x04 \x01(\bR\averbose\"\x15\n" +
	"\x13KernelStatusRequest\"\xfb\x01\n" +
	"\fKernelStatus\x12\x16\n" +
	"\x06cloned\x18\x01 \x01(\bR\x06cloned\x12\x1e\n" +
	"\n" +
	"configured\x18\x02 \x01(\bR\n" +
	"configured\x12\x14\n" +
	"\x05built\x18\x03 \x01(\bR\x05built\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x1d\n" +
	"\n" +
	"image_path\x18\x06 \x01(\tR\timagePath\x12(\n" +
	"\x10image_size_bytes\x18\a \x01(\x03R\x0eimageSizeBytes\x12&\n" +
	"\x0flast_build_time\x18\b \x01(\tR\rlastBuildTime\"+\n" +
	"\x13ListVersionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"2\n" +
	"\x14ListVersionsResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\tR\bversions2\x9a\x03\n" +
	"\rKernelService\x12:\n" +
	"\x05Clone\x12\x16.elmos.v1.CloneRequest\x1a\x17.elmos.v1.CloneProgress0\x01\x12D\n" +
	"\tConfigure\x12\x1a.elmos.v1.ConfigureRequest\x1a\x1b.elmos.v1.ConfigureResponse\x12:\n" +
	"\x05Build\x12\x16.elmos.v1.BuildRequest\x1a\x17.elmos.v1.BuildProgress0\x01\x128\n" +
	"\x05Clean\x12\x16.elmos.v1.CleanRequest\x1a\x17.elmos.v1.CleanResponse\x12B\n" +
	"\tGetStatus\x12\x1d.elmos.v1.KernelStatusRequest\x1a\x16.elmos.v1.KernelStatus\x12M\n" +
	"\fListVersions\x12\x1d.elmos.v1.ListVersionsRequest\x1a\x1e.elmos.v1.ListVersionsResponseB8Z6github.com/NguyenTrongPhuc552003/elmos/api/proto;protob\x06proto3"

var (
	file_api_proto_kernel_proto_rawDescOnce sync.Once
	file_api_proto_kernel_proto_rawDescData []byte
)

func file_api_proto_kernel_proto_rawDescGZIP() []byte {
	file_api_proto_kernel_proto_rawDescOnce.Do(func() {
		file_api_proto_kernel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kernel_proto_rawDesc), len(file_api_proto_kernel_proto_rawDesc)))
	})
	return file_api_proto_kernel_proto_rawDescData
}

var file_api_proto_kernel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_kernel_proto_goTypes = []any{
	(*CloneRequest)(nil),         // 0: elmos.v1.CloneRequest
	(*CloneProgress)(nil),        // 1: elmos.v1.CloneProgress
	(*ConfigureRequest)(nil),     // 2: elmos.v1.ConfigureRequest
	(*ConfigureResponse)(nil),    // 3: elmos.v1.ConfigureResponse
	(*BuildRequest)(nil),         // 4: elmos.v1.BuildRequest
	(*KernelStatusRequest)(nil),  // 5: elmos.v1.KernelStatusRequest
	(*KernelStatus)(nil),         // 6: elmos.v1.KernelStatus
	(*ListVersionsRequest)(nil),  // 7: elmos.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil), // 8: elmos.v1.ListVersionsResponse
	nil,                          // 9: elmos.v1.ConfigureRequest.OptionsEntry
	(*CleanRequest)(nil),         // 10: elmos.v1.CleanRequest
	(*BuildProgress)(nil),        // 11: elmos.v1.BuildProgress
	(*CleanResponse)(nil),        // 12: elmos.v1.CleanResponse
}
var file_api_proto_kernel_proto_depIdxs = []int32{
	9,  // 0: elmos.v1.ConfigureRequest.options:type_name -> elmos.v1.ConfigureRequest.OptionsEntry
	0,  // 1: elmos.v1.KernelService.Clone:input_type -> elmos.v1.CloneRequest
	2,  // 2: elmos.v1.KernelService.Configure:input_type -> elmos.v1.ConfigureRequest
	4,  // 3: elmos.v1.KernelService.Build:input_type -> elmos.v1.BuildRequest
	10, // 4: elmos.v1.KernelService.Clean:input_type -> elmos.v1.CleanRequest
	5,  // 5: elmos.v1.KernelService.GetStatus:input_type -> elmos.v1.KernelStatusRequest
	7,  // 6: elmos.v1.KernelService.ListVersions:input_type -> elmos.v1.ListVersionsRequest
	1,  // 7: elmos.v1.KernelService.Clone:output_type -> elmos.v1.CloneProgress
	3,  // 8: elmos.v1.KernelService.Configure:output_type -> elmos.v1.ConfigureResponse
	11, // 9: elmos.v1.KernelService.Build:output_type -> elmos.v1.BuildProgress
	12, // 10: elmos.v1.KernelService.Clean:output_type -> elmos.v1.CleanResponse
	6,  // 11: elmos.v1.KernelService.GetStatus:output_type -> elmos.v1.KernelStatus
	8,  // 12: elmos.v1.KernelService.ListVersions:output_type -> elmos.v1.ListVersionsResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_kernel_proto_init() }
func file_api_proto_kernel_proto_init() {
	if File_api_proto_kernel_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kernel_proto_rawDesc), len(file_api_proto_kernel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_kernel_proto_goTypes,
		DependencyIndexes: file_api_proto_kernel_proto_depIdxs,
		MessageInfos:      file_api_proto_kernel_proto_msgTypes,
	}.Build()
	File_api_proto_kernel_proto = out.File
	file_api_proto_kernel_proto_goTypes = nil
	file_api_proto_kernel_proto_depIdxs = nil
}
