// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/qemu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QEMURunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graphical     bool                   `protobuf:"varint,1,opt,name=graphical,proto3" json:"graphical,omitempty"`                             // Launch with graphical console
	Debug         bool                   `protobuf:"varint,2,opt,name=debug,proto3" json:"debug,omitempty"`                                     // Enable GDB debugging (port 1234)
	MemoryMb      int32                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`               // RAM size in MB (0 = default)
	Cpus          int32                  `protobuf:"varint,4,opt,name=cpus,proto3" json:"cpus,omitempty"`                                       // Number of CPUs (0 = default)
	ExtraArgs     []string               `protobuf:"bytes,5,rep,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`             // Additional QEMU arguments
	KernelCmdline string                 `protobuf:"bytes,6,opt,name=kernel_cmdline,json=kernelCmdline,proto3" json:"kernel_cmdline,omitempty"` // Custom kernel command line
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMURunRequest) Reset() {
	*x = QEMURunRequest{}
	mi := &file_api_proto_qemu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMURunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMURunRequest) ProtoMessage() {}

func (x *QEMURunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMURunRequest.ProtoReflect.Descriptor instead.
func (*QEMURunRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{0}
}

func (x *QEMURunRequest) GetGraphical() bool {
	if x != nil {
		return x.Graphical
	}
	return false
}

func (x *QEMURunRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *QEMURunRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *QEMURunRequest) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *QEMURunRequest) GetExtraArgs() []string {
	if x != nil {
		return x.ExtraArgs
	}
	return nil
}

func (x *QEMURunRequest) GetKernelCmdline() string {
	if x != nil {
		return x.KernelCmdline
	}
	return ""
}

type QEMUOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*QEMUOutput_Started
	//	*QEMUOutput_Console
	//	*QEMUOutput_Stopped
	//	*QEMUOutput_Error
	Event         isQEMUOutput_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUOutput) Reset() {
	*x = QEMUOutput{}
	mi := &file_api_proto_qemu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUOutput) ProtoMessage() {}

func (x *QEMUOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUOutput.ProtoReflect.Descriptor instead.
func (*QEMUOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{1}
}

func (x *QEMUOutput) GetEvent() isQEMUOutput_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *QEMUOutput) GetStarted() *QEMUStarted {
	if x != nil {
		if x, ok := x.Event.(*QEMUOutput_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *QEMUOutput) GetConsole() *ConsoleOutput {
	if x != nil {
		if x, ok := x.Event.(*QEMUOutput_Console); ok {
			return x.Console
		}
	}
	return nil
}

func (x *QEMUOutput) GetStopped() *QEMUStopped {
	if x != nil {
		if x, ok := x.Event.(*QEMUOutput_Stopped); ok {
			return x.Stopped
		}
	}
	return nil
}

func (x *QEMUOutput) GetError() *QEMUError {
	if x != nil {
		if x, ok := x.Event.(*QEMUOutput_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isQEMUOutput_Event interface {
	isQEMUOutput_Event()
}

type QEMUOutput_Started struct {
	Started *QEMUStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type QEMUOutput_Console struct {
	Console *ConsoleOutput `protobuf:"bytes,2,opt,name=console,proto3,oneof"`
}

type QEMUOutput_Stopped struct {
	Stopped *QEMUStopped `protobuf:"bytes,3,opt,name=stopped,proto3,oneof"`
}

type QEMUOutput_Error struct {
	Error *QEMUError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*QEMUOutput_Started) isQEMUOutput_Event() {}

func (*QEMUOutput_Console) isQEMUOutput_Event() {}

func (*QEMUOutput_Stopped) isQEMUOutput_Event() {}

func (*QEMUOutput_Error) isQEMUOutput_Event() {}

type QEMUStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	QemuVersion   string                 `protobuf:"bytes,2,opt,name=qemu_version,json=qemuVersion,proto3" json:"qemu_version,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // Full QEMU command line
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUStarted) Reset() {
	*x = QEMUStarted{}
	mi := &file_api_proto_qemu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUStarted) ProtoMessage() {}

func (x *QEMUStarted) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUStarted.ProtoReflect.Descriptor instead.
func (*QEMUStarted) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{2}
}

func (x *QEMUStarted) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *QEMUStarted) GetQemuVersion() string {
	if x != nil {
		return x.QemuVersion
	}
	return ""
}

func (x *QEMUStarted) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ConsoleOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Raw console bytes (for terminal emulator)
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleOutput) Reset() {
	*x = ConsoleOutput{}
	mi := &file_api_proto_qemu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleOutput) ProtoMessage() {}

func (x *ConsoleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleOutput.ProtoReflect.Descriptor instead.
func (*ConsoleOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{3}
}

func (x *ConsoleOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConsoleOutput) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type QEMUStopped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,2,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUStopped) Reset() {
	*x = QEMUStopped{}
	mi := &file_api_proto_qemu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUStopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUStopped) ProtoMessage() {}

func (x *QEMUStopped) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUStopped.ProtoReflect.Descriptor instead.
func (*QEMUStopped) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{4}
}

func (x *QEMUStopped) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *QEMUStopped) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

type QEMUError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUError) Reset() {
	*x = QEMUError{}
	mi := &file_api_proto_qemu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUError) ProtoMessage() {}

func (x *QEMUError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUError.ProtoReflect.Descriptor instead.
func (*QEMUError) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{5}
}

func (x *QEMUError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QEMUStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUStopRequest) Reset() {
	*x = QEMUStopRequest{}
	mi := &file_api_proto_qemu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUStopRequest) ProtoMessage() {}

func (x *QEMUStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUStopRequest.ProtoReflect.Descriptor instead.
func (*QEMUStopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{6}
}

type QEMUStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUStopResponse) Reset() {
	*x = QEMUStopResponse{}
	mi := &file_api_proto_qemu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUStopResponse) ProtoMessage() {}

func (x *QEMUStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUStopResponse.ProtoReflect.Descriptor instead.
func (*QEMUStopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{7}
}

func (x *QEMUStopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QEMUStopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QEMUInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Input bytes to send
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUInputRequest) Reset() {
	*x = QEMUInputRequest{}
	mi := &file_api_proto_qemu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUInputRequest) ProtoMessage() {}

func (x *QEMUInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUInputRequest.ProtoReflect.Descriptor instead.
func (*QEMUInputRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{8}
}

func (x *QEMUInputRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type QEMUInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUInputResponse) Reset() {
	*x = QEMUInputResponse{}
	mi := &file_api_proto_qemu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUInputResponse) ProtoMessage() {}

func (x *QEMUInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUInputResponse.ProtoReflect.Descriptor instead.
func (*QEMUInputResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{9}
}

func (x *QEMUInputResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type QEMUStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUStatusRequest) Reset() {
	*x = QEMUStatusRequest{}
	mi := &file_api_proto_qemu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUStatusRequest) ProtoMessage() {}

func (x *QEMUStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUStatusRequest.ProtoReflect.Descriptor instead.
func (*QEMUStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{10}
}

type QEMUStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Cpus          int32                  `protobuf:"varint,6,opt,name=cpus,proto3" json:"cpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QEMUStatus) Reset() {
	*x = QEMUStatus{}
	mi := &file_api_proto_qemu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QEMUStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QEMUStatus) ProtoMessage() {}

func (x *QEMUStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_qemu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QEMUStatus.ProtoReflect.Descriptor instead.
func (*QEMUStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_qemu_proto_rawDescGZIP(), []int{11}
}

func (x *QEMUStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *QEMUStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *QEMUStatus) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *QEMUStatus) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *QEMUStatus) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *QEMUStatus) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

var File_api_proto_qemu_proto protoreflect.FileDescriptor

const file_api_proto_qemu_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/qemu.proto\x12\belmos.v1\"\xbb\x01\n" +
	"\x0eQEMURunRequest\x12\x1c\n" +
	"\tgraphical\x18\x01 \x01(\bR\tgraphical\x12\x14\n" +
	"\x05debug\x18\x02 \x01(\bR\x05debug\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\x12\x12\n" +
	"\x04cpus\x18\x04 \x01(\x05R\x04cpus\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x05 \x03(\tR\textraArgs\x12%\n" +
	"\x0ekernel_cmdline\x18\x06 \x01(\tR\rkernelCmdline\"\xdd\x01\n" +
	"\n" +
	"QEMUOutput\x121\n" +
	"\astarted\x18\x01 \x01(\v2\x15.elmos.v1.QEMUStartedH\x00R\astarted\x123\n" +
	"\aconsole\x18\x02 \x01(\v2\x17.elmos.v1.ConsoleOutputH\x00R\aconsole\x121\n" +
	"\astopped\x18\x03 \x01(\v2\x15.elmos.v1.QEMUStoppedH\x00R\astopped\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.elmos.v1.QEMUErrorH\x00R\x05errorB\a\n" +
	"\x05event\"\\\n" +
	"\vQEMUStarted\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12!\n" +
	"\fqemu_version\x18\x02 \x01(\tR\vqemuVersion\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"F\n" +
	"\rConsoleOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"G\n" +
	"\vQEMUStopped\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1b\n" +
	"\tuptime_ms\x18\x02 \x01(\x03R\buptimeMs\"%\n" +
	"\tQEMUError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x11\n" +
	"\x0fQEMUStopRequest\"F\n" +
	"\x10QEMUStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x10QEMUInputRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"-\n" +
	"\x11QEMUInputResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11QEMUStatusRequest\"\x9a\x01\n" +
	"\n" +
	"QEMUStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x05R\bmemoryMb\x12\x12\n" +
	"\x04cpus\x18\x06 \x01(\x05R\x04cpus2\x8b\x02\n" +
	"\vQEMUService\x127\n" +
	"\x03Run\x12\x18.elmos.v1.QEMURunRequest\x1a\x14.elmos.v1.QEMUOutput0\x01\x12=\n" +
	"\x04Stop\x12\x19.elmos.v1.QEMUStopRequest\x1a\x1a.elmos.v1.QEMUStopResponse\x12D\n" +
	"\tSendInput\x12\x1a.elmos.v1.QEMUInputRequest\x1a\x1b.elmos.v1.QEMUInputResponse\x12>\n" +
	"\tGetStatus\x12\x1b.elmos.v1.QEMUStatusRequest\x1a\x14.elmos.v1.QEMUStatusB8Z6github.com/NguyenTrongPhuc552003/elmos/api/proto;protob\x06proto3"

var (
	file_api_proto_qemu_proto_rawDescOnce sync.Once
	file_api_proto_qemu_proto_rawDescData []byte
)

func file_api_proto_qemu_proto_rawDescGZIP() []byte {
	file_api_proto_qemu_proto_rawDescOnce.Do(func() {
		file_api_proto_qemu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_qemu_proto_rawDesc), len(file_api_proto_qemu_proto_rawDesc)))
	})
	return file_api_proto_qemu_proto_rawDescData
}

var file_api_proto_qemu_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_qemu_proto_goTypes = []any{
	(*QEMURunRequest)(nil),    // 0: elmos.v1.QEMURunRequest
	(*QEMUOutput)(nil),        // 1: elmos.v1.QEMUOutput
	(*QEMUStarted)(nil),       // 2: elmos.v1.QEMUStarted
	(*ConsoleOutput)(nil),     // 3: elmos.v1.ConsoleOutput
	(*QEMUStopped)(nil),       // 4: elmos.v1.QEMUStopped
	(*QEMUError)(nil),         // 5: elmos.v1.QEMUError
	(*QEMUStopRequest)(nil),   // 6: elmos.v1.QEMUStopRequest
	(*QEMUStopResponse)(nil),  // 7: elmos.v1.QEMUStopResponse
	(*QEMUInputRequest)(nil),  // 8: elmos.v1.QEMUInputRequest
	(*QEMUInputResponse)(nil), // 9: elmos.v1.QEMUInputResponse
	(*QEMUStatusRequest)(nil), // 10: elmos.v1.QEMUStatusRequest
	(*QEMUStatus)(nil),        // 11: elmos.v1.QEMUStatus
}
var file_api_proto_qemu_proto_depIdxs = []int32{
	2,  // 0: elmos.v1.QEMUOutput.started:type_name -> elmos.v1.QEMUStarted
	3,  // 1: elmos.v1.QEMUOutput.console:type_name -> elmos.v1.ConsoleOutput
	4,  // 2: elmos.v1.QEMUOutput.stopped:type_name -> elmos.v1.QEMUStopped
	5,  // 3: elmos.v1.QEMUOutput.error:type_name -> elmos.v1.QEMUError
	0,  // 4: elmos.v1.QEMUService.Run:input_type -> elmos.v1.QEMURunRequest
	6,  // 5: elmos.v1.QEMUService.Stop:input_type -> elmos.v1.QEMUStopRequest
	8,  // 6: elmos.v1.QEMUService.SendInput:input_type -> elmos.v1.QEMUInputRequest
	10, // 7: elmos.v1.QEMUService.GetStatus:input_type -> elmos.v1.QEMUStatusRequest
	1,  // 8: elmos.v1.QEMUService.Run:output_type -> elmos.v1.QEMUOutput
	7,  // 9: elmos.v1.QEMUService.Stop:output_type -> elmos.v1.QEMUStopResponse
	9,  // 10: elmos.v1.QEMUService.SendInput:output_type -> elmos.v1.QEMUInputResponse
	11, // 11: elmos.v1.QEMUService.GetStatus:output_type -> elmos.v1.QEMUStatus
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_qemu_proto_init() }
func file_api_proto_qemu_proto_init() {
	if File_api_proto_qemu_proto != nil {
		return
	}
	file_api_proto_qemu_proto_msgTypes[1].OneofWrappers = []any{
		(*QEMUOutput_Started)(nil),
		(*QEMUOutput_Console)(nil),
		(*QEMUOutput_Stopped)(nil),
		(*QEMUOutput_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_qemu_proto_rawDesc), len(file_api_proto_qemu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_qemu_proto_goTypes,
		DependencyIndexes: file_api_proto_qemu_proto_depIdxs,
		MessageInfos:      file_api_proto_qemu_proto_msgTypes,
	}.Build()
	File_api_proto_qemu_proto = out.File
	file_api_proto_qemu_proto_goTypes = nil
	file_api_proto_qemu_proto_depIdxs = nil
}
