// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/qemu.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QEMUService_Run_FullMethodName       = "/elmos.v1.QEMUService/Run"
	QEMUService_Stop_FullMethodName      = "/elmos.v1.QEMUService/Stop"
	QEMUService_SendInput_FullMethodName = "/elmos.v1.QEMUService/SendInput"
	QEMUService_GetStatus_FullMethodName = "/elmos.v1.QEMUService/GetStatus"
)

// QEMUServiceClient is the client API for QEMUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QEMUService manages QEMU emulator operations.
type QEMUServiceClient interface {
	// Run runs QEMU with streaming console output.
	Run(ctx context.Context, in *QEMURunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QEMUOutput], error)
	// Stop stops the running QEMU instance.
	Stop(ctx context.Context, in *QEMUStopRequest, opts ...grpc.CallOption) (*QEMUStopResponse, error)
	// SendInput sends input to the QEMU console.
	SendInput(ctx context.Context, in *QEMUInputRequest, opts ...grpc.CallOption) (*QEMUInputResponse, error)
	// GetStatus returns the QEMU instance status.
	GetStatus(ctx context.Context, in *QEMUStatusRequest, opts ...grpc.CallOption) (*QEMUStatus, error)
}

type qEMUServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQEMUServiceClient(cc grpc.ClientConnInterface) QEMUServiceClient {
	return &qEMUServiceClient{cc}
}

func (c *qEMUServiceClient) Run(ctx context.Context, in *QEMURunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QEMUOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QEMUService_ServiceDesc.Streams[0], QEMUService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QEMURunRequest, QEMUOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QEMUService_RunClient = grpc.ServerStreamingClient[QEMUOutput]

func (c *qEMUServiceClient) Stop(ctx context.Context, in *QEMUStopRequest, opts ...grpc.CallOption) (*QEMUStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QEMUStopResponse)
	err := c.cc.Invoke(ctx, QEMUService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qEMUServiceClient) SendInput(ctx context.Context, in *QEMUInputRequest, opts ...grpc.CallOption) (*QEMUInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QEMUInputResponse)
	err := c.cc.Invoke(ctx, QEMUService_SendInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qEMUServiceClient) GetStatus(ctx context.Context, in *QEMUStatusRequest, opts ...grpc.CallOption) (*QEMUStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QEMUStatus)
	err := c.cc.Invoke(ctx, QEMUService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QEMUServiceServer is the server API for QEMUService service.
// All implementations must embed UnimplementedQEMUServiceServer
// for forward compatibility.
//
// QEMUService manages QEMU emulator operations.
type QEMUServiceServer interface {
	// Run runs QEMU with streaming console output.
	Run(*QEMURunRequest, grpc.ServerStreamingServer[QEMUOutput]) error
	// Stop stops the running QEMU instance.
	Stop(context.Context, *QEMUStopRequest) (*QEMUStopResponse, error)
	// SendInput sends input to the QEMU console.
	SendInput(context.Context, *QEMUInputRequest) (*QEMUInputResponse, error)
	// GetStatus returns the QEMU instance status.
	GetStatus(context.Context, *QEMUStatusRequest) (*QEMUStatus, error)
	mustEmbedUnimplementedQEMUServiceServer()
}

// UnimplementedQEMUServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQEMUServiceServer struct{}

func (UnimplementedQEMUServiceServer) Run(*QEMURunRequest, grpc.ServerStreamingServer[QEMUOutput]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedQEMUServiceServer) Stop(context.Context, *QEMUStopRequest) (*QEMUStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedQEMUServiceServer) SendInput(context.Context, *QEMUInputRequest) (*QEMUInputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendInput not implemented")
}
func (UnimplementedQEMUServiceServer) GetStatus(context.Context, *QEMUStatusRequest) (*QEMUStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedQEMUServiceServer) mustEmbedUnimplementedQEMUServiceServer() {}
func (UnimplementedQEMUServiceServer) testEmbeddedByValue()                     {}

// UnsafeQEMUServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QEMUServiceServer will
// result in compilation errors.
type UnsafeQEMUServiceServer interface {
	mustEmbedUnimplementedQEMUServiceServer()
}

func RegisterQEMUServiceServer(s grpc.ServiceRegistrar, srv QEMUServiceServer) {
	// If the following call panics, it indicates UnimplementedQEMUServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QEMUService_ServiceDesc, srv)
}

func _QEMUService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QEMURunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QEMUServiceServer).Run(m, &grpc.GenericServerStream[QEMURunRequest, QEMUOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QEMUService_RunServer = grpc.ServerStreamingServer[QEMUOutput]

func _QEMUService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QEMUStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEMUServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEMUService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEMUServiceServer).Stop(ctx, req.(*QEMUStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QEMUService_SendInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QEMUInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEMUServiceServer).SendInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEMUService_SendInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEMUServiceServer).SendInput(ctx, req.(*QEMUInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QEMUService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QEMUStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEMUServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEMUService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEMUServiceServer).GetStatus(ctx, req.(*QEMUStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QEMUService_ServiceDesc is the grpc.ServiceDesc for QEMUService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QEMUService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "elmos.v1.QEMUService",
	HandlerType: (*QEMUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _QEMUService_Stop_Handler,
		},
		{
			MethodName: "SendInput",
			Handler:    _QEMUService_SendInput_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _QEMUService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _QEMUService_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/qemu.proto",
}
