// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/toolchain.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolchainService_Install_FullMethodName      = "/elmos.v1.ToolchainService/Install"
	ToolchainService_ListSamples_FullMethodName  = "/elmos.v1.ToolchainService/ListSamples"
	ToolchainService_SelectTarget_FullMethodName = "/elmos.v1.ToolchainService/SelectTarget"
	ToolchainService_Build_FullMethodName        = "/elmos.v1.ToolchainService/Build"
	ToolchainService_GetStatus_FullMethodName    = "/elmos.v1.ToolchainService/GetStatus"
	ToolchainService_Clean_FullMethodName        = "/elmos.v1.ToolchainService/Clean"
)

// ToolchainServiceClient is the client API for ToolchainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToolchainService manages crosstool-ng toolchain operations.
type ToolchainServiceClient interface {
	// Install installs crosstool-ng.
	Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstallProgress], error)
	// ListSamples lists available toolchain targets.
	ListSamples(ctx context.Context, in *ListSamplesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SampleTarget], error)
	// SelectTarget selects a toolchain target.
	SelectTarget(ctx context.Context, in *SelectTargetRequest, opts ...grpc.CallOption) (*SelectTargetResponse, error)
	// Build builds the selected toolchain with streaming progress.
	Build(ctx context.Context, in *BuildToolchainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildProgress], error)
	// GetStatus returns toolchain installation status.
	GetStatus(ctx context.Context, in *ToolchainStatusRequest, opts ...grpc.CallOption) (*ToolchainStatusResponse, error)
	// Clean cleans toolchain build artifacts.
	Clean(ctx context.Context, in *CleanRequest, opts ...grpc.CallOption) (*CleanResponse, error)
}

type toolchainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolchainServiceClient(cc grpc.ClientConnInterface) ToolchainServiceClient {
	return &toolchainServiceClient{cc}
}

func (c *toolchainServiceClient) Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstallProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolchainService_ServiceDesc.Streams[0], ToolchainService_Install_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallRequest, InstallProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolchainService_InstallClient = grpc.ServerStreamingClient[InstallProgress]

func (c *toolchainServiceClient) ListSamples(ctx context.Context, in *ListSamplesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SampleTarget], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolchainService_ServiceDesc.Streams[1], ToolchainService_ListSamples_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListSamplesRequest, SampleTarget]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolchainService_ListSamplesClient = grpc.ServerStreamingClient[SampleTarget]

func (c *toolchainServiceClient) SelectTarget(ctx context.Context, in *SelectTargetRequest, opts ...grpc.CallOption) (*SelectTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectTargetResponse)
	err := c.cc.Invoke(ctx, ToolchainService_SelectTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolchainServiceClient) Build(ctx context.Context, in *BuildToolchainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolchainService_ServiceDesc.Streams[2], ToolchainService_Build_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildToolchainRequest, BuildProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolchainService_BuildClient = grpc.ServerStreamingClient[BuildProgress]

func (c *toolchainServiceClient) GetStatus(ctx context.Context, in *ToolchainStatusRequest, opts ...grpc.CallOption) (*ToolchainStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolchainStatusResponse)
	err := c.cc.Invoke(ctx, ToolchainService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolchainServiceClient) Clean(ctx context.Context, in *CleanRequest, opts ...grpc.CallOption) (*CleanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanResponse)
	err := c.cc.Invoke(ctx, ToolchainService_Clean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolchainServiceServer is the server API for ToolchainService service.
// All implementations must embed UnimplementedToolchainServiceServer
// for forward compatibility.
//
// ToolchainService manages crosstool-ng toolchain operations.
type ToolchainServiceServer interface {
	// Install installs crosstool-ng.
	Install(*InstallRequest, grpc.ServerStreamingServer[InstallProgress]) error
	// ListSamples lists available toolchain targets.
	ListSamples(*ListSamplesRequest, grpc.ServerStreamingServer[SampleTarget]) error
	// SelectTarget selects a toolchain target.
	SelectTarget(context.Context, *SelectTargetRequest) (*SelectTargetResponse, error)
	// Build builds the selected toolchain with streaming progress.
	Build(*BuildToolchainRequest, grpc.ServerStreamingServer[BuildProgress]) error
	// GetStatus returns toolchain installation status.
	GetStatus(context.Context, *ToolchainStatusRequest) (*ToolchainStatusResponse, error)
	// Clean cleans toolchain build artifacts.
	Clean(context.Context, *CleanRequest) (*CleanResponse, error)
	mustEmbedUnimplementedToolchainServiceServer()
}

// UnimplementedToolchainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolchainServiceServer struct{}

func (UnimplementedToolchainServiceServer) Install(*InstallRequest, grpc.ServerStreamingServer[InstallProgress]) error {
	return status.Error(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedToolchainServiceServer) ListSamples(*ListSamplesRequest, grpc.ServerStreamingServer[SampleTarget]) error {
	return status.Error(codes.Unimplemented, "method ListSamples not implemented")
}
func (UnimplementedToolchainServiceServer) SelectTarget(context.Context, *SelectTargetRequest) (*SelectTargetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectTarget not implemented")
}
func (UnimplementedToolchainServiceServer) Build(*BuildToolchainRequest, grpc.ServerStreamingServer[BuildProgress]) error {
	return status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedToolchainServiceServer) GetStatus(context.Context, *ToolchainStatusRequest) (*ToolchainStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedToolchainServiceServer) Clean(context.Context, *CleanRequest) (*CleanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clean not implemented")
}
func (UnimplementedToolchainServiceServer) mustEmbedUnimplementedToolchainServiceServer() {}
func (UnimplementedToolchainServiceServer) testEmbeddedByValue()                          {}

// UnsafeToolchainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolchainServiceServer will
// result in compilation errors.
type UnsafeToolchainServiceServer interface {
	mustEmbedUnimplementedToolchainServiceServer()
}

func RegisterToolchainServiceServer(s grpc.ServiceRegistrar, srv ToolchainServiceServer) {
	// If the following call panics, it indicates UnimplementedToolchainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolchainService_ServiceDesc, srv)
}

func _ToolchainService_Install_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToolchainServiceServer).Install(m, &grpc.GenericServerStream[InstallRequest, InstallProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolchainService_InstallServer = grpc.ServerStreamingServer[InstallProgress]

func _ToolchainService_ListSamples_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSamplesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToolchainServiceServer).ListSamples(m, &grpc.GenericServerStream[ListSamplesRequest, SampleTarget]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolchainService_ListSamplesServer = grpc.ServerStreamingServer[SampleTarget]

func _ToolchainService_SelectTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolchainServiceServer).SelectTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolchainService_SelectTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolchainServiceServer).SelectTarget(ctx, req.(*SelectTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolchainService_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildToolchainRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToolchainServiceServer).Build(m, &grpc.GenericServerStream[BuildToolchainRequest, BuildProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolchainService_BuildServer = grpc.ServerStreamingServer[BuildProgress]

func _ToolchainService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolchainStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolchainServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolchainService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolchainServiceServer).GetStatus(ctx, req.(*ToolchainStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolchainService_Clean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolchainServiceServer).Clean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolchainService_Clean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolchainServiceServer).Clean(ctx, req.(*CleanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolchainService_ServiceDesc is the grpc.ServiceDesc for ToolchainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolchainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "elmos.v1.ToolchainService",
	HandlerType: (*ToolchainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectTarget",
			Handler:    _ToolchainService_SelectTarget_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ToolchainService_GetStatus_Handler,
		},
		{
			MethodName: "Clean",
			Handler:    _ToolchainService_Clean_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Install",
			Handler:       _ToolchainService_Install_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSamples",
			Handler:       _ToolchainService_ListSamples_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Build",
			Handler:       _ToolchainService_Build_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/toolchain.proto",
}
