// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/toolchain.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallProgress_Stage int32

const (
	InstallProgress_DOWNLOADING InstallProgress_Stage = 0
	InstallProgress_EXTRACTING  InstallProgress_Stage = 1
	InstallProgress_CONFIGURING InstallProgress_Stage = 2
	InstallProgress_BUILDING    InstallProgress_Stage = 3
	InstallProgress_INSTALLING  InstallProgress_Stage = 4
	InstallProgress_COMPLETE    InstallProgress_Stage = 5
)

// Enum value maps for InstallProgress_Stage.
var (
	InstallProgress_Stage_name = map[int32]string{
		0: "DOWNLOADING",
		1: "EXTRACTING",
		2: "CONFIGURING",
		3: "BUILDING",
		4: "INSTALLING",
		5: "COMPLETE",
	}
	InstallProgress_Stage_value = map[string]int32{
		"DOWNLOADING": 0,
		"EXTRACTING":  1,
		"CONFIGURING": 2,
		"BUILDING":    3,
		"INSTALLING":  4,
		"COMPLETE":    5,
	}
)

func (x InstallProgress_Stage) Enum() *InstallProgress_Stage {
	p := new(InstallProgress_Stage)
	*p = x
	return p
}

func (x InstallProgress_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallProgress_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_toolchain_proto_enumTypes[0].Descriptor()
}

func (InstallProgress_Stage) Type() protoreflect.EnumType {
	return &file_api_proto_toolchain_proto_enumTypes[0]
}

func (x InstallProgress_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallProgress_Stage.Descriptor instead.
func (InstallProgress_Stage) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{1, 0}
}

type InstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_api_proto_toolchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{0}
}

type InstallProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         InstallProgress_Stage  `protobuf:"varint,1,opt,name=stage,proto3,enum=elmos.v1.InstallProgress_Stage" json:"stage,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallProgress) Reset() {
	*x = InstallProgress{}
	mi := &file_api_proto_toolchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallProgress) ProtoMessage() {}

func (x *InstallProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallProgress.ProtoReflect.Descriptor instead.
func (*InstallProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{1}
}

func (x *InstallProgress) GetStage() InstallProgress_Stage {
	if x != nil {
		return x.Stage
	}
	return InstallProgress_DOWNLOADING
}

func (x *InstallProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *InstallProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListSamplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSamplesRequest) Reset() {
	*x = ListSamplesRequest{}
	mi := &file_api_proto_toolchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSamplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSamplesRequest) ProtoMessage() {}

func (x *ListSamplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSamplesRequest.ProtoReflect.Descriptor instead.
func (*ListSamplesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{2}
}

type SampleTarget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                 // e.g., "riscv64-unknown-linux-gnu"
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                   // Human-readable description
	HasCustomConfig bool                   `protobuf:"varint,3,opt,name=has_custom_config,json=hasCustomConfig,proto3" json:"has_custom_config,omitempty"` // Whether custom config exists
	Arch            string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`                                                 // Target architecture
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SampleTarget) Reset() {
	*x = SampleTarget{}
	mi := &file_api_proto_toolchain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleTarget) ProtoMessage() {}

func (x *SampleTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleTarget.ProtoReflect.Descriptor instead.
func (*SampleTarget) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{3}
}

func (x *SampleTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SampleTarget) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SampleTarget) GetHasCustomConfig() bool {
	if x != nil {
		return x.HasCustomConfig
	}
	return false
}

func (x *SampleTarget) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type SelectTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // Target name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectTargetRequest) Reset() {
	*x = SelectTargetRequest{}
	mi := &file_api_proto_toolchain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectTargetRequest) ProtoMessage() {}

func (x *SelectTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectTargetRequest.ProtoReflect.Descriptor instead.
func (*SelectTargetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{4}
}

func (x *SelectTargetRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type SelectTargetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,3,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"` // Path to generated config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectTargetResponse) Reset() {
	*x = SelectTargetResponse{}
	mi := &file_api_proto_toolchain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectTargetResponse) ProtoMessage() {}

func (x *SelectTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectTargetResponse.ProtoReflect.Descriptor instead.
func (*SelectTargetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{5}
}

func (x *SelectTargetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SelectTargetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SelectTargetResponse) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type BuildToolchainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          int32                  `protobuf:"varint,1,opt,name=jobs,proto3" json:"jobs,omitempty"` // Parallel jobs (0 = auto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildToolchainRequest) Reset() {
	*x = BuildToolchainRequest{}
	mi := &file_api_proto_toolchain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildToolchainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildToolchainRequest) ProtoMessage() {}

func (x *BuildToolchainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildToolchainRequest.ProtoReflect.Descriptor instead.
func (*BuildToolchainRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{6}
}

func (x *BuildToolchainRequest) GetJobs() int32 {
	if x != nil {
		return x.Jobs
	}
	return 0
}

type ToolchainStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolchainStatusRequest) Reset() {
	*x = ToolchainStatusRequest{}
	mi := &file_api_proto_toolchain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolchainStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolchainStatusRequest) ProtoMessage() {}

func (x *ToolchainStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolchainStatusRequest.ProtoReflect.Descriptor instead.
func (*ToolchainStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{7}
}

type ToolchainStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CrosstoolNgInstalled bool                   `protobuf:"varint,1,opt,name=crosstool_ng_installed,json=crosstoolNgInstalled,proto3" json:"crosstool_ng_installed,omitempty"`
	CrosstoolNgVersion   string                 `protobuf:"bytes,2,opt,name=crosstool_ng_version,json=crosstoolNgVersion,proto3" json:"crosstool_ng_version,omitempty"`
	Installed            []*ToolchainInfo       `protobuf:"bytes,3,rep,name=installed,proto3" json:"installed,omitempty"`
	SelectedTarget       string                 `protobuf:"bytes,4,opt,name=selected_target,json=selectedTarget,proto3" json:"selected_target,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolchainStatusResponse) Reset() {
	*x = ToolchainStatusResponse{}
	mi := &file_api_proto_toolchain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolchainStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolchainStatusResponse) ProtoMessage() {}

func (x *ToolchainStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolchainStatusResponse.ProtoReflect.Descriptor instead.
func (*ToolchainStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{8}
}

func (x *ToolchainStatusResponse) GetCrosstoolNgInstalled() bool {
	if x != nil {
		return x.CrosstoolNgInstalled
	}
	return false
}

func (x *ToolchainStatusResponse) GetCrosstoolNgVersion() string {
	if x != nil {
		return x.CrosstoolNgVersion
	}
	return ""
}

func (x *ToolchainStatusResponse) GetInstalled() []*ToolchainInfo {
	if x != nil {
		return x.Installed
	}
	return nil
}

func (x *ToolchainStatusResponse) GetSelectedTarget() string {
	if x != nil {
		return x.SelectedTarget
	}
	return ""
}

type ToolchainInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	GccVersion    string                 `protobuf:"bytes,2,opt,name=gcc_version,json=gccVersion,proto3" json:"gcc_version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	FullyBuilt    bool                   `protobuf:"varint,4,opt,name=fully_built,json=fullyBuilt,proto3" json:"fully_built,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolchainInfo) Reset() {
	*x = ToolchainInfo{}
	mi := &file_api_proto_toolchain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolchainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolchainInfo) ProtoMessage() {}

func (x *ToolchainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_toolchain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolchainInfo.ProtoReflect.Descriptor instead.
func (*ToolchainInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_toolchain_proto_rawDescGZIP(), []int{9}
}

func (x *ToolchainInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ToolchainInfo) GetGccVersion() string {
	if x != nil {
		return x.GccVersion
	}
	return ""
}

func (x *ToolchainInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ToolchainInfo) GetFullyBuilt() bool {
	if x != nil {
		return x.FullyBuilt
	}
	return false
}

func (x *ToolchainInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

var File_api_proto_toolchain_proto protoreflect.FileDescriptor

const file_api_proto_toolchain_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/toolchain.proto\x12\belmos.v1\x1a\x16api/proto/common.proto\"\x10\n" +
	"\x0eInstallRequest\"\xe5\x01\n" +
	"\x0fInstallProgress\x125\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x1f.elmos.v1.InstallProgress.StageR\x05stage\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"e\n" +
	"\x05Stage\x12\x0f\n" +
	"\vDOWNLOADING\x10\x00\x12\x0e\n" +
	"\n" +
	"EXTRACTING\x10\x01\x12\x0f\n" +
	"\vCONFIGURING\x10\x02\x12\f\n" +
	"\bBUILDING\x10\x03\x12\x0e\n" +
	"\n" +
	"INSTALLING\x10\x04\x12\f\n" +
	"\bCOMPLETE\x10\x05\"\x14\n" +
	"\x12ListSamplesRequest\"\x84\x01\n" +
	"\fSampleTarget\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11has_custom_config\x18\x03 \x01(\bR\x0fhasCustomConfig\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\"-\n" +
	"\x13SelectTargetRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"v\n" +
	"\x14SelectTargetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vconfig_path\x18\x03 \x01(\tR\n" +
	"configPath\"+\n" +
	"\x15BuildToolchainRequest\x12\x12\n" +
	"\x04jobs\x18\x01 \x01(\x05R\x04jobs\"\x18\n" +
	"\x16ToolchainStatusRequest\"\xe1\x01\n" +
	"\x17ToolchainStatusResponse\x124\n" +
	"\x16crosstool_ng_installed\x18\x01 \x01(\bR\x14crosstoolNgInstalled\x120\n" +
	"\x14crosstool_ng_version\x18\x02 \x01(\tR\x12crosstoolNgVersion\x125\n" +
	"\tinstalled\x18\x03 \x03(\v2\x17.elmos.v1.ToolchainInfoR\tinstalled\x12'\n" +
	"\x0fselected_target\x18\x04 \x01(\tR\x0eselectedTarget\"\x9c\x01\n" +
	"\rToolchainInfo\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1f\n" +
	"\vgcc_version\x18\x02 \x01(\tR\n" +
	"gccVersion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1f\n" +
	"\vfully_built\x18\x04 \x01(\bR\n" +
	"fullyBuilt\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes2\xbb\x03\n" +
	"\x10ToolchainService\x12@\n" +
	"\aInstall\x12\x18.elmos.v1.InstallRequest\x1a\x19.elmos.v1.InstallProgress0\x01\x12E\n" +
	"\vListSamples\x12\x1c.elmos.v1.ListSamplesRequest\x1a\x16.elmos.v1.SampleTarget0\x01\x12M\n" +
	"\fSelectTarget\x12\x1d.elmos.v1.SelectTargetRequest\x1a\x1e.elmos.v1.SelectTargetResponse\x12C\n" +
	"\x05Build\x12\x1f.elmos.v1.BuildToolchainRequest\x1a\x17.elmos.v1.BuildProgress0\x01\x12P\n" +
	"\tGetStatus\x12 .elmos.v1.ToolchainStatusRequest\x1a!.elmos.v1.ToolchainStatusResponse\x128\n" +
	"\x05Clean\x12\x16.elmos.v1.CleanRequest\x1a\x17.elmos.v1.CleanResponseB8Z6github.com/NguyenTrongPhuc552003/elmos/api/proto;protob\x06proto3"

var (
	file_api_proto_toolchain_proto_rawDescOnce sync.Once
	file_api_proto_toolchain_proto_rawDescData []byte
)

func file_api_proto_toolchain_proto_rawDescGZIP() []byte {
	file_api_proto_toolchain_proto_rawDescOnce.Do(func() {
		file_api_proto_toolchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_toolchain_proto_rawDesc), len(file_api_proto_toolchain_proto_rawDesc)))
	})
	return file_api_proto_toolchain_proto_rawDescData
}

var file_api_proto_toolchain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_toolchain_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_toolchain_proto_goTypes = []any{
	(InstallProgress_Stage)(0),      // 0: elmos.v1.InstallProgress.Stage
	(*InstallRequest)(nil),          // 1: elmos.v1.InstallRequest
	(*InstallProgress)(nil),         // 2: elmos.v1.InstallProgress
	(*ListSamplesRequest)(nil),      // 3: elmos.v1.ListSamplesRequest
	(*SampleTarget)(nil),            // 4: elmos.v1.SampleTarget
	(*SelectTargetRequest)(nil),     // 5: elmos.v1.SelectTargetRequest
	(*SelectTargetResponse)(nil),    // 6: elmos.v1.SelectTargetResponse
	(*BuildToolchainRequest)(nil),   // 7: elmos.v1.BuildToolchainRequest
	(*ToolchainStatusRequest)(nil),  // 8: elmos.v1.ToolchainStatusRequest
	(*ToolchainStatusResponse)(nil), // 9: elmos.v1.ToolchainStatusResponse
	(*ToolchainInfo)(nil),           // 10: elmos.v1.ToolchainInfo
	(*CleanRequest)(nil),            // 11: elmos.v1.CleanRequest
	(*BuildProgress)(nil),           // 12: elmos.v1.BuildProgress
	(*CleanResponse)(nil),           // 13: elmos.v1.CleanResponse
}
var file_api_proto_toolchain_proto_depIdxs = []int32{
	0,  // 0: elmos.v1.InstallProgress.stage:type_name -> elmos.v1.InstallProgress.Stage
	10, // 1: elmos.v1.ToolchainStatusResponse.installed:type_name -> elmos.v1.ToolchainInfo
	1,  // 2: elmos.v1.ToolchainService.Install:input_type -> elmos.v1.InstallRequest
	3,  // 3: elmos.v1.ToolchainService.ListSamples:input_type -> elmos.v1.ListSamplesRequest
	5,  // 4: elmos.v1.ToolchainService.SelectTarget:input_type -> elmos.v1.SelectTargetRequest
	7,  // 5: elmos.v1.ToolchainService.Build:input_type -> elmos.v1.BuildToolchainRequest
	8,  // 6: elmos.v1.ToolchainService.GetStatus:input_type -> elmos.v1.ToolchainStatusRequest
	11, // 7: elmos.v1.ToolchainService.Clean:input_type -> elmos.v1.CleanRequest
	2,  // 8: elmos.v1.ToolchainService.Install:output_type -> elmos.v1.InstallProgress
	4,  // 9: elmos.v1.ToolchainService.ListSamples:output_type -> elmos.v1.SampleTarget
	6,  // 10: elmos.v1.ToolchainService.SelectTarget:output_type -> elmos.v1.SelectTargetResponse
	12, // 11: elmos.v1.ToolchainService.Build:output_type -> elmos.v1.BuildProgress
	9,  // 12: elmos.v1.ToolchainService.GetStatus:output_type -> elmos.v1.ToolchainStatusResponse
	13, // 13: elmos.v1.ToolchainService.Clean:output_type -> elmos.v1.CleanResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_toolchain_proto_init() }
func file_api_proto_toolchain_proto_init() {
	if File_api_proto_toolchain_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_toolchain_proto_rawDesc), len(file_api_proto_toolchain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_toolchain_proto_goTypes,
		DependencyIndexes: file_api_proto_toolchain_proto_depIdxs,
		EnumInfos:         file_api_proto_toolchain_proto_enumTypes,
		MessageInfos:      file_api_proto_toolchain_proto_msgTypes,
	}.Build()
	File_api_proto_toolchain_proto = out.File
	file_api_proto_toolchain_proto_goTypes = nil
	file_api_proto_toolchain_proto_depIdxs = nil
}
