// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/workspace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitProgress_Stage int32

const (
	InitProgress_VALIDATING      InitProgress_Stage = 0
	InitProgress_CREATING_VOLUME InitProgress_Stage = 1
	InitProgress_MOUNTING        InitProgress_Stage = 2
	InitProgress_SAVING_CONFIG   InitProgress_Stage = 3
	InitProgress_COMPLETE        InitProgress_Stage = 4
)

// Enum value maps for InitProgress_Stage.
var (
	InitProgress_Stage_name = map[int32]string{
		0: "VALIDATING",
		1: "CREATING_VOLUME",
		2: "MOUNTING",
		3: "SAVING_CONFIG",
		4: "COMPLETE",
	}
	InitProgress_Stage_value = map[string]int32{
		"VALIDATING":      0,
		"CREATING_VOLUME": 1,
		"MOUNTING":        2,
		"SAVING_CONFIG":   3,
		"COMPLETE":        4,
	}
)

func (x InitProgress_Stage) Enum() *InitProgress_Stage {
	p := new(InitProgress_Stage)
	*p = x
	return p
}

func (x InitProgress_Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InitProgress_Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_workspace_proto_enumTypes[0].Descriptor()
}

func (InitProgress_Stage) Type() protoreflect.EnumType {
	return &file_api_proto_workspace_proto_enumTypes[0]
}

func (x InitProgress_Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InitProgress_Stage.Descriptor instead.
func (InitProgress_Stage) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{1, 0}
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Workspace name (default: "elmos")
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"` // Volume size (e.g., "40G")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_api_proto_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type InitProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         InitProgress_Stage     `protobuf:"varint,1,opt,name=stage,proto3,enum=elmos.v1.InitProgress_Stage" json:"stage,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`    // Human-readable status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitProgress) Reset() {
	*x = InitProgress{}
	mi := &file_api_proto_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitProgress) ProtoMessage() {}

func (x *InitProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitProgress.ProtoReflect.Descriptor instead.
func (*InitProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *InitProgress) GetStage() InitProgress_Stage {
	if x != nil {
		return x.Stage
	}
	return InitProgress_VALIDATING
}

func (x *InitProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *InitProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumePath    string                 `protobuf:"bytes,1,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"` // Path to volume file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_api_proto_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *MountRequest) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

type MountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_api_proto_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *MountResponse) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *MountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UnmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Force unmount if busy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountRequest) Reset() {
	*x = UnmountRequest{}
	mi := &file_api_proto_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountRequest) ProtoMessage() {}

func (x *UnmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountRequest.ProtoReflect.Descriptor instead.
func (*UnmountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *UnmountRequest) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *UnmountRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type UnmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountResponse) Reset() {
	*x = UnmountResponse{}
	mi := &file_api_proto_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountResponse) ProtoMessage() {}

func (x *UnmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountResponse.ProtoReflect.Descriptor instead.
func (*UnmountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *UnmountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnmountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type WorkspaceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceStatusRequest) Reset() {
	*x = WorkspaceStatusRequest{}
	mi := &file_api_proto_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceStatusRequest) ProtoMessage() {}

func (x *WorkspaceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceStatusRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{6}
}

type WorkspaceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mounted       bool                   `protobuf:"varint,1,opt,name=mounted,proto3" json:"mounted,omitempty"`
	MountPoint    string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	VolumePath    string                 `protobuf:"bytes,3,opt,name=volume_path,json=volumePath,proto3" json:"volume_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	UsedBytes     int64                  `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	AvailBytes    int64                  `protobuf:"varint,6,opt,name=avail_bytes,json=availBytes,proto3" json:"avail_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceStatus) Reset() {
	*x = WorkspaceStatus{}
	mi := &file_api_proto_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceStatus) ProtoMessage() {}

func (x *WorkspaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceStatus.ProtoReflect.Descriptor instead.
func (*WorkspaceStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *WorkspaceStatus) GetMounted() bool {
	if x != nil {
		return x.Mounted
	}
	return false
}

func (x *WorkspaceStatus) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *WorkspaceStatus) GetVolumePath() string {
	if x != nil {
		return x.VolumePath
	}
	return ""
}

func (x *WorkspaceStatus) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *WorkspaceStatus) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *WorkspaceStatus) GetAvailBytes() int64 {
	if x != nil {
		return x.AvailBytes
	}
	return 0
}

var File_api_proto_workspace_proto protoreflect.FileDescriptor

const file_api_proto_workspace_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/workspace.proto\x12\belmos.v1\"5\n" +
	"\vInitRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\"\xd5\x01\n" +
	"\fInitProgress\x122\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x1c.elmos.v1.InitProgress.StageR\x05stage\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"[\n" +
	"\x05Stage\x12\x0e\n" +
	"\n" +
	"VALIDATING\x10\x00\x12\x13\n" +
	"\x0fCREATING_VOLUME\x10\x01\x12\f\n" +
	"\bMOUNTING\x10\x02\x12\x11\n" +
	"\rSAVING_CONFIG\x10\x03\x12\f\n" +
	"\bCOMPLETE\x10\x04\"/\n" +
	"\fMountRequest\x12\x1f\n" +
	"\vvolume_path\x18\x01 \x01(\tR\n" +
	"volumePath\"o\n" +
	"\rMountResponse\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"G\n" +
	"\x0eUnmountRequest\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"P\n" +
	"\x0fUnmountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x18\n" +
	"\x16WorkspaceStatusRequest\"\xcc\x01\n" +
	"\x0fWorkspaceStatus\x12\x18\n" +
	"\amounted\x18\x01 \x01(\bR\amounted\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x1f\n" +
	"\vvolume_path\x18\x03 \x01(\tR\n" +
	"volumePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x03R\tusedBytes\x12\x1f\n" +
	"\vavail_bytes\x18\x06 \x01(\x03R\n" +
	"availBytes2\x8f\x02\n" +
	"\x10WorkspaceService\x127\n" +
	"\x04Init\x12\x15.elmos.v1.InitRequest\x1a\x16.elmos.v1.InitProgress0\x01\x128\n" +
	"\x05Mount\x12\x16.elmos.v1.MountRequest\x1a\x17.elmos.v1.MountResponse\x12>\n" +
	"\aUnmount\x12\x18.elmos.v1.UnmountRequest\x1a\x19.elmos.v1.UnmountResponse\x12H\n" +
	"\tGetStatus\x12 .elmos.v1.WorkspaceStatusRequest\x1a\x19.elmos.v1.WorkspaceStatusB8Z6github.com/NguyenTrongPhuc552003/elmos/api/proto;protob\x06proto3"

var (
	file_api_proto_workspace_proto_rawDescOnce sync.Once
	file_api_proto_workspace_proto_rawDescData []byte
)

func file_api_proto_workspace_proto_rawDescGZIP() []byte {
	file_api_proto_workspace_proto_rawDescOnce.Do(func() {
		file_api_proto_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_workspace_proto_rawDesc), len(file_api_proto_workspace_proto_rawDesc)))
	})
	return file_api_proto_workspace_proto_rawDescData
}

var file_api_proto_workspace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_workspace_proto_goTypes = []any{
	(InitProgress_Stage)(0),        // 0: elmos.v1.InitProgress.Stage
	(*InitRequest)(nil),            // 1: elmos.v1.InitRequest
	(*InitProgress)(nil),           // 2: elmos.v1.InitProgress
	(*MountRequest)(nil),           // 3: elmos.v1.MountRequest
	(*MountResponse)(nil),          // 4: elmos.v1.MountResponse
	(*UnmountRequest)(nil),         // 5: elmos.v1.UnmountRequest
	(*UnmountResponse)(nil),        // 6: elmos.v1.UnmountResponse
	(*WorkspaceStatusRequest)(nil), // 7: elmos.v1.WorkspaceStatusRequest
	(*WorkspaceStatus)(nil),        // 8: elmos.v1.WorkspaceStatus
}
var file_api_proto_workspace_proto_depIdxs = []int32{
	0, // 0: elmos.v1.InitProgress.stage:type_name -> elmos.v1.InitProgress.Stage
	1, // 1: elmos.v1.WorkspaceService.Init:input_type -> elmos.v1.InitRequest
	3, // 2: elmos.v1.WorkspaceService.Mount:input_type -> elmos.v1.MountRequest
	5, // 3: elmos.v1.WorkspaceService.Unmount:input_type -> elmos.v1.UnmountRequest
	7, // 4: elmos.v1.WorkspaceService.GetStatus:input_type -> elmos.v1.WorkspaceStatusRequest
	2, // 5: elmos.v1.WorkspaceService.Init:output_type -> elmos.v1.InitProgress
	4, // 6: elmos.v1.WorkspaceService.Mount:output_type -> elmos.v1.MountResponse
	6, // 7: elmos.v1.WorkspaceService.Unmount:output_type -> elmos.v1.UnmountResponse
	8, // 8: elmos.v1.WorkspaceService.GetStatus:output_type -> elmos.v1.WorkspaceStatus
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_workspace_proto_init() }
func file_api_proto_workspace_proto_init() {
	if File_api_proto_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_workspace_proto_rawDesc), len(file_api_proto_workspace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_workspace_proto_goTypes,
		DependencyIndexes: file_api_proto_workspace_proto_depIdxs,
		EnumInfos:         file_api_proto_workspace_proto_enumTypes,
		MessageInfos:      file_api_proto_workspace_proto_msgTypes,
	}.Build()
	File_api_proto_workspace_proto = out.File
	file_api_proto_workspace_proto_goTypes = nil
	file_api_proto_workspace_proto_depIdxs = nil
}
